version: '3.8'

services:
  backend:
    build: ./backend
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://jay-velog.cvac2usy0eap.ap-southeast-2.rds.amazonaws.com:3306/velog_db
      - SPRING_DATASOURCE_USERNAME=jay
      - SPRING_DATASOURCE_PASSWORD=Jayvelog0315
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
